"""
Vulture allowlist — symbols reported as unused that are intentionally kept.

Vulture scans only the application source (`src/spellbot` and `scripts`), not the test
suite, so any source symbol exercised solely by tests looks unused to it. It also can't see
references made through framework conventions, type-only annotations, TypedDict keys, or
Jinja templates. Referencing a name here marks it "used" so vulture stops reporting it.

Check with `uv run vulture`; regenerate candidates with `uv run vulture --make-whitelist`.
Prefer deleting genuinely dead code over adding it here.
"""

from __future__ import annotations

_.color  # unused attribute (src/spellbot/actions/admin_action.py:60)
_.color  # unused attribute (src/spellbot/actions/admin_action.py:104)
_.color  # unused attribute (src/spellbot/actions/admin_action.py:114)
_.color  # unused attribute (src/spellbot/actions/admin_action.py:237)
_.color  # unused attribute (src/spellbot/actions/admin_action.py:332)
_.color  # unused attribute (src/spellbot/actions/lfg_action.py:692)
_.color  # unused attribute (src/spellbot/actions/lfg_action.py:708)
_.color  # unused attribute (src/spellbot/actions/lfg_action.py:860)
_.color  # unused attribute (src/spellbot/actions/record_action.py:36)
_.color  # unused attribute (src/spellbot/actions/record_action.py:51)
_.color  # unused attribute (src/spellbot/actions/record_action.py:83)
_.color  # unused attribute (src/spellbot/actions/watch_action.py:127)
install  # unused function (src/spellbot/audit.py:119)
attach_triggers  # unused function (src/spellbot/audit.py:129)
uninstall  # unused function (src/spellbot/audit.py:146)
_.message_content  # unused attribute (src/spellbot/client.py:87)
_.messages  # unused attribute (src/spellbot/client.py:88)
_.fetch_application_emojis  # unused attribute (src/spellbot/client.py:313)
_.color  # unused attribute (src/spellbot/cogs/about_cog.py:47)
_.color  # unused attribute (src/spellbot/data/game_data.py:234)
_.color  # unused attribute (src/spellbot/data/game_data.py:240)
__class_getitem__  # unused function (src/spellbot/database.py:35)
rollback_transaction  # unused function (src/spellbot/database.py:201)
roomName  # unused variable (src/spellbot/integrations/tablestream.py:67)
gameType  # unused variable (src/spellbot/integrations/tablestream.py:68)
maxPlayers  # unused variable (src/spellbot/integrations/tablestream.py:69)
initialScheduleTTLInSeconds  # unused variable (src/spellbot/integrations/tablestream.py:81)
_.__aenter__  # unused attribute (tests/cogs/test_playgroup_cog.py:105)
_.__aenter__  # unused attribute (tests/integrations/test_convoke.py:349)
_.__aenter__  # unused attribute (tests/integrations/test_convoke.py:381)
_.__aenter__  # unused attribute (tests/integrations/test_convoke.py:417)
_.__aenter__  # unused attribute (tests/integrations/test_edhlab.py:130)
_.__aenter__  # unused attribute (tests/integrations/test_edhlab.py:158)
_.__aenter__  # unused attribute (tests/integrations/test_edhlab.py:189)
auth_count  # unused variable (tests/integrations/test_girudo.py:798)
auth_count  # unused variable (tests/integrations/test_girudo.py:802)
_.__aenter__  # unused attribute (tests/integrations/test_playgroup_live.py:385)
_.__aenter__  # unused attribute (tests/integrations/test_playgroup_live.py:418)
_.__aenter__  # unused attribute (tests/integrations/test_tablestream.py:194)
_.__aenter__  # unused attribute (tests/integrations/test_tablestream.py:219)
_.__aenter__  # unused attribute (tests/services/test_guilds.py:365)
_.__aenter__  # unused attribute (tests/services/test_guilds.py:380)
_.__aenter__  # unused attribute (tests/services/test_guilds.py:395)
_.__aenter__  # unused attribute (tests/services/test_guilds.py:406)
_.__aenter__  # unused attribute (tests/services/test_patreon.py:294)
_.__aenter__  # unused attribute (tests/services/test_patreon.py:314)
_.__aenter__  # unused attribute (tests/services/test_patreon.py:328)
_.__aenter__  # unused attribute (tests/test_bot.py:690)
_.__aenter__  # unused attribute (tests/test_bot.py:715)
_.__aenter__  # unused attribute (tests/test_bot.py:748)
_.zremrangebyscore  # unused attribute (tests/test_dm_limiter.py:141)
_.zcard  # unused attribute (tests/test_dm_limiter.py:142)
_.zremrangebyscore  # unused attribute (tests/test_dm_limiter.py:161)
_.zcard  # unused attribute (tests/test_dm_limiter.py:162)
_.side_effect  # unused attribute (tests/test_operations.py:100)
_.side_effect  # unused attribute (tests/test_operations.py:109)
_.side_effect  # unused attribute (tests/test_operations.py:117)
_.side_effect  # unused attribute (tests/test_operations.py:126)
_.side_effect  # unused attribute (tests/test_operations.py:135)
_.side_effect  # unused attribute (tests/test_operations.py:294)
_.side_effect  # unused attribute (tests/test_operations.py:302)
_.side_effect  # unused attribute (tests/test_operations.py:314)
_.side_effect  # unused attribute (tests/test_operations.py:330)
_.side_effect  # unused attribute (tests/test_operations.py:373)
_.side_effect  # unused attribute (tests/test_operations.py:460)
_.__str__  # unused attribute (tests/test_operations.py:629)
_.__str__  # unused attribute (tests/test_operations.py:644)
_.__str__  # unused attribute (tests/test_operations.py:652)
_.__str__  # unused attribute (tests/test_operations.py:663)
_.__str__  # unused attribute (tests/test_operations.py:672)
_.__str__  # unused attribute (tests/test_operations.py:681)
_.__str__  # unused attribute (tests/test_operations.py:690)
_.__str__  # unused attribute (tests/test_operations.py:708)
_.__str__  # unused attribute (tests/test_operations.py:802)
_.__str__  # unused attribute (tests/test_operations.py:884)
_.side_effect  # unused attribute (tests/test_shard_status.py:290)
_.side_effect  # unused attribute (tests/test_shard_status.py:416)
_.__aenter__  # unused attribute (tests/web/conftest.py:60)
_.__aenter__  # unused attribute (tests/web/test_admin_auth.py:198)
_.testcheck_guild_member_api_error  # unused method (tests/web/test_analytics.py:540)
_.__aenter__  # unused attribute (tests/web/test_analytics.py:547)
_.testcheck_guild_member_success  # unused method (tests/web/test_analytics.py:555)
_.__aenter__  # unused attribute (tests/web/test_analytics.py:563)
_.testcheck_guild_member_not_found  # unused method (tests/web/test_analytics.py:571)
_.__aenter__  # unused attribute (tests/web/test_analytics.py:579)
_.testcheck_guild_member_rate_limited  # unused method (tests/web/test_analytics.py:587)
_.__aenter__  # unused attribute (tests/web/test_analytics.py:595)
_.__aenter__  # unused attribute (tests/web/test_dashboard.py:35)
_.__aenter__  # unused attribute (tests/web/test_moderation.py:20)
_.__aenter__  # unused attribute (tests/web/test_moderation.py:129)
_.__aenter__  # unused attribute (tests/web/test_queues.py:1623)
_.__aenter__  # unused attribute (tests/web/test_rest.py:285)
_.__aenter__  # unused attribute (tests/web/test_rest.py:300)
_._value_  # unused attribute (src/spellbot/enums.py:20)
_._value_  # unused attribute (src/spellbot/enums.py:90)
_._value_  # unused attribute (src/spellbot/enums.py:163)
