{
 "title": "SpellBot",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total  Games",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "command": "get", "type": "command" }
   ]
  },
  {
   "title": "Games Created Recently",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "command": "get", "type": "command" },
    { "command": "get", "type": "command" },
    { "command": "get", "type": "command" },
    { "command": "get", "type": "command" },
    { "command": "get", "type": "command" }
   ]
  },
  {
   "title": "Users Joined Recently",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "command": "get", "type": "command" },
    { "command": "get", "type": "command" },
    { "command": "get", "type": "command" },
    { "command": "get", "type": "command" },
    { "command": "get", "type": "command" }
   ]
  },
  {
   "title": "Servers Added Recently",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "command": "get", "type": "command" },
    { "command": "get", "type": "command" },
    { "command": "get", "type": "command" },
    { "command": "get", "type": "command" },
    { "command": "get", "type": "command" }
   ]
  },
  {
   "title": "Power Levels",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    ROUND(\n        (SELECT 1.0 * COUNT(id) FROM games WHERE ROUND(game_power) = 1.0) /\n        (SELECT 1.0 * COUNT(id) FROM games WHERE game_power IS NOT NULL) * 100\n    ) AS \"p1\"\n\n    , ROUND(\n        (SELECT 1.0 * COUNT(id) FROM games WHERE ROUND(game_power) = 2.0) /\n        (SELECT 1.0 * COUNT(id) FROM games WHERE game_power IS NOT NULL) * 100\n    ) AS \"p2\"\n\n    , ROUND(\n        (SELECT 1.0 * COUNT(id) FROM games WHERE ROUND(game_power) = 3.0) /\n        (SELECT 1.0 * COUNT(id) FROM games WHERE game_power IS NOT NULL) * 100\n    ) AS \"p3\"\n\n    , ROUND(\n        (SELECT 1.0 * COUNT(id) FROM games WHERE ROUND(game_power) = 4.0) /\n        (SELECT 1.0 * COUNT(id) FROM games WHERE game_power IS NOT NULL) * 100\n    ) AS \"p4\"\n\n    , ROUND(\n        (SELECT 1.0 * COUNT(id) FROM games WHERE ROUND(game_power) = 5.0) /\n        (SELECT 1.0 * COUNT(id) FROM games WHERE game_power IS NOT NULL) * 100\n    ) AS \"p5\"\n\n    , ROUND(\n        (SELECT 1.0 * COUNT(id) FROM games WHERE ROUND(game_power) = 6.0) /\n        (SELECT 1.0 * COUNT(id) FROM games WHERE game_power IS NOT NULL) * 100\n    ) AS \"p6\"\n\n    , ROUND(\n        (SELECT 1.0 * COUNT(id) FROM games WHERE ROUND(game_power) = 7.0) /\n        (SELECT 1.0 * COUNT(id) FROM games WHERE game_power IS NOT NULL) * 100\n    ) AS \"p7\"\n\n    , ROUND(\n        (SELECT 1.0 * COUNT(id) FROM games WHERE ROUND(game_power) = 8.0) /\n        (SELECT 1.0 * COUNT(id) FROM games WHERE game_power IS NOT NULL) * 100\n    ) AS \"p8\"\n\n    , ROUND(\n        (SELECT 1.0 * COUNT(id) FROM games WHERE ROUND(game_power) = 9.0) /\n        (SELECT 1.0 * COUNT(id) FROM games WHERE game_power IS NOT NULL) * 100\n    ) AS \"p9\"\n\n    , ROUND(\n        (SELECT 1.0 * COUNT(id) FROM games WHERE ROUND(game_power) = 10.0) /\n        (SELECT 1.0 * COUNT(id) FROM games WHERE game_power IS NOT NULL) * 100\n    ) AS \"p10\"\n;\n"
    }
   ]
  },
  {
   "title": "Total  Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "command": "get", "type": "command" }
   ]
  },
  {
   "title": "Total Servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "command": "get", "type": "command" }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Daily Users Joined",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1d),\n  count(xid) AS \"count\"\nFROM users\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Daily Active Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(updated_at,1d),\n  count(xid) AS \"count\"\nFROM users\nWHERE\n  $__timeFilter(updated_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Weekly Active Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(updated_at,7d),\n  count(xid) AS \"count\"\nFROM users\nWHERE\n  $__timeFilter(updated_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Monthly Active Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(updated_at,30d),\n  count(xid) AS \"count\"\nFROM users\nWHERE\n  $__timeFilter(updated_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DAU:MAU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT (\n        SELECT AVG(DAU.count)\n        FROM (\n                SELECT count(xid) AS \"count\"\n                FROM users\n                WHERE $__timeFilter(updated_at)\n                GROUP BY floor(extract(epoch from updated_at)/86400)*86400\n                ORDER BY floor(extract(epoch from updated_at)/86400)*86400\n        ) DAU\n    ) / (\n        SELECT AVG(MAU.count)\n        FROM (\n                SELECT count(xid) AS \"count\"\n                FROM users\n                WHERE $__timeFilter(updated_at)\n                GROUP BY floor(extract(epoch from updated_at)/2.592e+06)*2.592e+06\n                ORDER BY floor(extract(epoch from updated_at)/2.592e+06)*2.592e+06\n        ) MAU\n    ) * 100.0\n"
    }
   ]
  },
  { "title": "Games", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Daily Games Created",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1d),\n  count(id) AS \"count\"\nFROM games\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Hourly Games Created",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  count(id) AS \"count\"\nFROM games\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Daily Power Level Games Created",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1d),\n  count(id) AS \"count\"\nFROM games\nWHERE\n  $__timeFilter(created_at) AND\n  game_power > 0\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Hourly Average Queue Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroupAlias(created_at,1h)\n    , EXTRACT(EPOCH FROM (AVG(updated_at - created_at))) / 60.0 AS \"minutes\"\nFROM games\nWHERE \n    status = 'started'\n    AND $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Daily Average Queue Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroupAlias(created_at,1d)\n    , EXTRACT(EPOCH FROM (AVG(updated_at - created_at))) / 60.0 AS \"minutes\"\nFROM games\nWHERE \n    status = 'started'\n    AND $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  { "title": "Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Daily Servers Added",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1d),\n  count(guild_xid) AS \"count\"\nFROM servers\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Weekly Server Popularity",
   "type": "graph",
   "gridPos": { "h": 24, "w": 20, "x": 4, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  servers.cached_name AS \"server\",\n  $__timeGroupAlias(games.created_at,7d),\n  count(games.id) AS \"count\"\nFROM games\nJOIN servers ON servers.guild_xid = games.guild_xid\nWHERE\n  $__timeFilter(games.created_at) AND\n  servers.cached_name IS NOT NULL\nGROUP BY 1, 2\n-- HAVING count(games.id) > 5\nORDER BY 1, 2"
    }
   ]
  },
  { "title": "PlayEDH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Daily Games Created",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1d),\n  count(id) AS \"count\"\nFROM games\nWHERE\n  $__timeFilter(created_at) AND\n  guild_xid = 304276578005942272\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Hourly Games Created",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  count(id) AS \"count\"\nFROM games\nWHERE\n  $__timeFilter(created_at) AND\n  guild_xid = 304276578005942272\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Hourly Channel Popularity",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    channel_settings.cached_name\n    , $__timeGroupAlias(games.created_at,1h)\n    , COUNT(games.id) AS \"count\"\nFROM games\nJOIN channel_settings\n    ON channel_settings.channel_xid = games.channel_xid\nWHERE\n  $__timeFilter(games.created_at) AND\n  games.guild_xid = 304276578005942272 AND\n  channel_settings.cached_name IS NOT NULL\nGROUP BY 1, 2\nORDER BY 1, 2\n"
    }
   ]
  },
  {
   "title": "Daily Channel Popularity",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    channel_settings.cached_name\n    , $__timeGroupAlias(games.created_at,1d)\n    , COUNT(games.id) AS \"count\"\nFROM games\nJOIN channel_settings\n    ON channel_settings.channel_xid = games.channel_xid\nWHERE\n  $__timeFilter(games.created_at) AND\n  games.guild_xid = 304276578005942272 AND\n  channel_settings.cached_name IS NOT NULL\nGROUP BY 1, 2\nORDER BY 1, 2\n"
    }
   ]
  },
  {
   "title": "Daily Average Queue Time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroupAlias(created_at,1d)\n    , EXTRACT(EPOCH FROM (AVG(updated_at - created_at))) / 60.0 AS \"minutes\"\nFROM games\nWHERE \n    status = 'started'\n    AND $__timeFilter(created_at)\n    AND guild_xid = 304276578005942272\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Hourly Average Queue Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroupAlias(created_at,1h)\n    , EXTRACT(EPOCH FROM (AVG(updated_at - created_at))) / 60.0 AS \"minutes\"\nFROM games\nWHERE \n    status = 'started'\n    AND $__timeFilter(created_at)\n    AND guild_xid = 304276578005942272\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Hourly Queue Times by Channel",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    channel_settings.cached_name\n    , $__timeGroupAlias(games.created_at,1h)\n    , EXTRACT(EPOCH FROM (AVG(games.updated_at - games.created_at))) / 60.0 AS \"minutes\"\nFROM games\nJOIN channel_settings\n    ON channel_settings.channel_xid = games.channel_xid\nWHERE\n  $__timeFilter(games.created_at) AND\n  games.guild_xid = 304276578005942272 AND\n  channel_settings.cached_name IS NOT NULL\nGROUP BY 1, 2\nORDER BY 1, 2\n"
    }
   ]
  },
  {
   "title": "Daily Queue Times by Channel",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    channel_settings.cached_name\n    , $__timeGroupAlias(games.created_at,1d)\n    , EXTRACT(EPOCH FROM (AVG(games.updated_at - games.created_at))) / 60.0 AS \"minutes\"\nFROM games\nJOIN channel_settings\n    ON channel_settings.channel_xid = games.channel_xid\nWHERE\n  $__timeFilter(games.created_at) AND\n  games.guild_xid = 304276578005942272 AND\n  channel_settings.cached_name IS NOT NULL\nGROUP BY 1, 2\nORDER BY 1, 2\n"
    }
   ]
  }
 ]
}