name: terraform

on:
  push:
    branches:
      - main
    paths:
      - "infrastructure/**"
  pull_request:
    branches:
      - main
    paths:
      - "infrastructure/**"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  TF_VERSION: "1.12"

jobs:
  validate:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

    strategy:
      matrix:
        directory:
          - infrastructure/app
          - infrastructure/db
          - infrastructure/o11y

    steps:
      - name: Checkout Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2
        with:
          tflint_version: latest

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: infrastructure

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: ${{ matrix.directory }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ matrix.directory }}

      - name: TFLint Init
        run: tflint --init
        working-directory: ${{ matrix.directory }}

      - name: TFLint
        run: tflint --format=compact
        working-directory: ${{ matrix.directory }}
